export type FieldType = "text" | "number" | "select" | "path" | "toggle";

export interface ConfField {
  name: string;
  value: string;
  is_commented: boolean;
  description: string;
  type: FieldType;
  options?: string[];
}

export interface ConfSection {
  title: string;
  fields: ConfField[];
}

export const POSTGRES_CONF_TEMPLATE: ConfSection[] = [
  {
    title: "FILE LOCATIONS",
    fields: [
      {
        name: "data_directory",
        value: "ConfigDir",
        is_commented: true,
        type: "path",
        description: "Specifies the directory to use for data storage.",
      },
      {
        name: "hba_file",
        value: "ConfigDir/pg_hba.conf",
        is_commented: true,
        type: "path",
        description: "Specifies the location of the host-based authentication file.",
      },
      {
        name: "ident_file",
        value: "ConfigDir/pg_ident.conf",
        is_commented: true,
        type: "path",
        description: "Specifies the location of the ident configuration file.",
      },
      {
        name: "external_pid_file",
        value: "",
        is_commented: true,
        type: "path",
        description: "Specifies an extra PID file that the server should write.",
      },
    ],
  },
  {
    title: "CONNECTIONS AND AUTHENTICATION",
    fields: [
      {
        name: "listen_addresses",
        value: "localhost",
        is_commented: true,
        type: "text",
        description: "Specifies the IP address(es) to listen on.",
        options: ["localhost", "*"],
      },
      {
        name: "port",
        value: "5432",
        is_commented: true,
        type: "number",
        description: "The TCP port on which the server listens.",
      },
      {
        name: "max_connections",
        value: "100",
        is_commented: false,
        type: "number",
        description: "Maximum number of concurrent connections to the database server.",
      },
      {
        name: "reserved_connections",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Number of connection slots reserved for non-superuser roles.",
      },
      {
        name: "superuser_reserved_connections",
        value: "3",
        is_commented: true,
        type: "number",
        description: "Number of connection slots reserved for superusers.",
      },
      {
        name: "unix_socket_directories",
        value: "",
        is_commented: true,
        type: "text",
        description: "Comma-separated list of directories for Unix-domain sockets.",
      },
      {
        name: "unix_socket_group",
        value: "",
        is_commented: true,
        type: "text",
        description: "Owning group of the Unix-domain sockets.",
      },
      {
        name: "unix_socket_permissions",
        value: "0777",
        is_commented: true,
        type: "text",
        description: "Access permissions of the Unix-domain sockets.",
      },
      {
        name: "bonjour",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Advertise server via Bonjour.",
        options: ["on", "off"],
      },
      {
        name: "bonjour_name",
        value: "",
        is_commented: true,
        type: "text",
        description: "Bonjour service name. Defaults to the computer name.",
      },
      {
        name: "tcp_keepalives_idle",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Time between keepalives (TCP_KEEPIDLE) in seconds.",
      },
      {
        name: "tcp_keepalives_interval",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Time between keepalive retransmits (TCP_KEEPINTVL) in seconds.",
      },
      {
        name: "tcp_keepalives_count",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Maximum number of keepalive retransmits (TCP_KEEPCNT).",
      },
      {
        name: "tcp_user_timeout",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Time before transmitted data is considered lost (TCP_USER_TIMEOUT) in milliseconds.",
      },
      {
        name: "client_connection_check_interval",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Time between checks for client disconnection while running queries.",
      },
      {
        name: "authentication_timeout",
        value: "1min",
        is_commented: true,
        type: "text",
        description: "Maximum time to complete client authentication.",
      },
      {
        name: "password_encryption",
        value: "scram-sha-256",
        is_commented: true,
        type: "select",
        description: "Algorithm to encrypt passwords.",
        options: ["scram-sha-256", "md5"],
      },
      {
        name: "scram_iterations",
        value: "4096",
        is_commented: true,
        type: "number",
        description: "Number of iterations for SCRAM password encryption.",
      },
      {
        name: "md5_password_warnings",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Display MD5 deprecation warnings.",
        options: ["on", "off"],
      },
      {
        name: "oauth_validator_libraries",
        value: "",
        is_commented: true,
        type: "text",
        description: "Comma-separated list of trusted OAuth validator modules.",
      },
      {
        name: "krb_server_keyfile",
        value: "FILE:${sysconfdir}/krb5.keytab",
        is_commented: true,
        type: "path",
        description: "Kerberos server keyfile.",
      },
      {
        name: "krb_caseins_users",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Treat Kerberos usernames as case-insensitive.",
        options: ["on", "off"],
      },
      {
        name: "gss_accept_delegation",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Allow GSSAPI credentials delegation.",
        options: ["on", "off"],
      },
      {
        name: "ssl",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Enables SSL connections.",
        options: ["on", "off"],
      },
      {
        name: "ssl_ca_file",
        value: "",
        is_commented: true,
        type: "path",
        description: "File containing SSL certificate authorities.",
      },
      {
        name: "ssl_cert_file",
        value: "server.crt",
        is_commented: true,
        type: "path",
        description: "File containing the SSL server certificate.",
      },
      {
        name: "ssl_crl_file",
        value: "",
        is_commented: true,
        type: "path",
        description: "File containing the SSL certificate revocation list.",
      },
      {
        name: "ssl_crl_dir",
        value: "",
        is_commented: true,
        type: "path",
        description: "Directory containing SSL certificate revocation lists.",
      },
      {
        name: "ssl_key_file",
        value: "server.key",
        is_commented: true,
        type: "path",
        description: "File containing the SSL server private key.",
      },
      {
        name: "ssl_ciphers",
        value: "HIGH:MEDIUM:+3DES:!aNULL",
        is_commented: true,
        type: "text",
        description: "Allowed TLSv1.2 ciphers.",
      },
      {
        name: "ssl_tls13_ciphers",
        value: "",
        is_commented: true,
        type: "text",
        description: "Allowed TLSv1.3 cipher suites.",
      },
      {
        name: "ssl_prefer_server_ciphers",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Prefer server's cipher suite order.",
        options: ["on", "off"],
      },
      {
        name: "ssl_groups",
        value: "X25519:prime256v1",
        is_commented: true,
        type: "text",
        description: "Allowed SSL curves/groups.",
      },
      {
        name: "ssl_min_protocol_version",
        value: "TLSv1.2",
        is_commented: true,
        type: "text",
        description: "Minimum allowed SSL/TLS protocol version.",
      },
      {
        name: "ssl_max_protocol_version",
        value: "",
        is_commented: true,
        type: "text",
        description: "Maximum allowed SSL/TLS protocol version.",
      },
      {
        name: "ssl_dh_params_file",
        value: "",
        is_commented: true,
        type: "path",
        description: "File containing Diffie-Hellman parameters.",
      },
      {
        name: "ssl_passphrase_command",
        value: "",
        is_commented: true,
        type: "text",
        description: "Command to obtain SSL private key passphrase.",
      },
      {
        name: "ssl_passphrase_command_supports_reload",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Allow reloading SSL configuration with passphrase command.",
        options: ["on", "off"],
      },
    ],
  },
  {
    title: "RESOURCE USAGE",
    fields: [
      {
        name: "shared_buffers",
        value: "128MB",
        is_commented: false,
        type: "text",
        description: "Memory used for shared memory buffers.",
      },
      {
        name: "huge_pages",
        value: "try",
        is_commented: true,
        type: "select",
        description: "Enables use of huge memory pages.",
        options: ["on", "off", "try"],
      },
      {
        name: "huge_page_size",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Size of huge memory pages; zero for system default.",
      },
      {
        name: "temp_buffers",
        value: "8MB",
        is_commented: true,
        type: "text",
        description: "Memory used for temporary buffers.",
      },
      {
        name: "max_prepared_transactions",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Maximum number of transactions that can be in the 'prepared' state.",
      },
      {
        name: "work_mem",
        value: "4MB",
        is_commented: true,
        type: "text",
        description: "Memory used by sort operations and hash tables.",
      },
      {
        name: "hash_mem_multiplier",
        value: "2.0",
        is_commented: true,
        type: "number",
        description: "Multiplier on hash table work_mem.",
      },
      {
        name: "maintenance_work_mem",
        value: "64MB",
        is_commented: true,
        type: "text",
        description: "Memory used by maintenance operations like VACUUM.",
      },
      {
        name: "autovacuum_work_mem",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Memory used by each autovacuum worker.",
      },
      {
        name: "logical_decoding_work_mem",
        value: "64MB",
        is_commented: true,
        type: "text",
        description: "Memory used by logical decoding before spilling to disk.",
      },
      {
        name: "max_stack_depth",
        value: "2MB",
        is_commented: true,
        type: "text",
        description: "Maximum safe depth of the server's execution stack.",
      },
      {
        name: "shared_memory_type",
        value: "mmap",
        is_commented: true,
        type: "select",
        description: "Implementation of shared memory.",
        options: ["mmap", "sysv", "windows"],
      },
      {
        name: "dynamic_shared_memory_type",
        value: "windows",
        is_commented: false,
        type: "select",
        description: "Implementation of dynamic shared memory.",
        options: ["posix", "sysv", "windows", "mmap"],
      },
      {
        name: "min_dynamic_shared_memory",
        value: "0MB",
        is_commented: true,
        type: "text",
        description: "Amount of dynamic shared memory allocated at server startup.",
      },
      {
        name: "vacuum_buffer_usage_limit",
        value: "2MB",
        is_commented: true,
        type: "text",
        description: "Size of vacuum and analyze buffer access strategy ring.",
      },
      {
        name: "commit_timestamp_buffers",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Memory for pg_commit_ts.",
      },
      {
        name: "multixact_offset_buffers",
        value: "16",
        is_commented: true,
        type: "number",
        description: "Memory for pg_multixact/offsets.",
      },
      {
        name: "multixact_member_buffers",
        value: "32",
        is_commented: true,
        type: "number",
        description: "Memory for pg_multixact/members.",
      },
      {
        name: "notify_buffers",
        value: "16",
        is_commented: true,
        type: "number",
        description: "Memory for pg_notify.",
      },
      {
        name: "serializable_buffers",
        value: "32",
        is_commented: true,
        type: "number",
        description: "Memory for pg_serial.",
      },
      {
        name: "subtransaction_buffers",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Memory for pg_subtrans.",
      },
      {
        name: "transaction_buffers",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Memory for pg_xact.",
      },
      {
        name: "temp_file_limit",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Limits per-process temp file space in kilobytes.",
      },
      {
        name: "file_copy_method",
        value: "copy",
        is_commented: true,
        type: "select",
        description: "Method used for file copying.",
        options: ["copy", "clone"],
      },
      {
        name: "file_extend_method",
        value: "posix_fallocate",
        is_commented: true,
        type: "select",
        description: "Method used for extending files.",
        options: ["posix_fallocate", "write_zeros"],
      },
      {
        name: "max_notify_queue_pages",
        value: "1048576",
        is_commented: true,
        type: "number",
        description: "Limits the number of SLRU pages allocated for NOTIFY / LISTEN queue.",
      },
      {
        name: "max_files_per_process",
        value: "1000",
        is_commented: true,
        type: "number",
        description: "Maximum number of file descriptors per process.",
      },
      {
        name: "bgwriter_delay",
        value: "200ms",
        is_commented: true,
        type: "text",
        description: "Time between background writer rounds.",
      },
      {
        name: "bgwriter_lru_maxpages",
        value: "100",
        is_commented: true,
        type: "number",
        description: "Maximum buffers written per background writer round.",
      },
      {
        name: "bgwriter_lru_multiplier",
        value: "2.0",
        is_commented: true,
        type: "number",
        description: "Multiplier on buffers scanned per background writer round.",
      },
      {
        name: "bgwriter_flush_after",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Pages to write before flushing via background writer.",
      },
      {
        name: "backend_flush_after",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Pages to write before flushing via backend.",
      },
      {
        name: "effective_io_concurrency",
        value: "16",
        is_commented: true,
        type: "number",
        description: "Number of simultaneous asynchronous I/O operations expected to be processed.",
      },
      {
        name: "maintenance_io_concurrency",
        value: "16",
        is_commented: true,
        type: "number",
        description: "I/O concurrency during maintenance operations.",
      },
      {
        name: "io_max_combine_limit",
        value: "128kB",
        is_commented: true,
        type: "text",
        description: "Maximum IO combine limit.",
      },
      {
        name: "io_combine_limit",
        value: "128kB",
        is_commented: true,
        type: "text",
        description: "Target IO combine limit.",
      },
      {
        name: "io_method",
        value: "worker",
        is_commented: true,
        type: "select",
        description: "Method for asynchronous I/O.",
        options: ["worker", "io_uring", "sync"],
      },
      {
        name: "io_max_concurrency",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Max number of IOs one process can execute simultaneously.",
      },
      {
        name: "io_workers",
        value: "3",
        is_commented: true,
        type: "number",
        description: "Number of I/O workers.",
      },
      {
        name: "max_worker_processes",
        value: "8",
        is_commented: true,
        type: "number",
        description: "Maximum number of background worker processes.",
      },
      {
        name: "max_parallel_workers_per_gather",
        value: "2",
        is_commented: true,
        type: "number",
        description: "Maximum number of parallel workers for a single query.",
      },
      {
        name: "max_parallel_maintenance_workers",
        value: "2",
        is_commented: true,
        type: "number",
        description: "Maximum parallel workers for maintenance operations.",
      },
      {
        name: "max_parallel_workers",
        value: "8",
        is_commented: true,
        type: "number",
        description: "Total maximum parallel workers.",
      },
      {
        name: "parallel_leader_participation",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Whether the leader participates in parallel queries.",
        options: ["on", "off"],
      },
    ],
  },
  {
    title: "WRITE-AHEAD LOG",
    fields: [
      {
        name: "wal_level",
        value: "replica",
        is_commented: true,
        type: "select",
        description: "Amount of data written to the WAL.",
        options: ["minimal", "replica", "logical"],
      },
      {
        name: "fsync",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Forces synchronization of updates to disk.",
        options: ["on", "off"],
      },
      {
        name: "synchronous_commit",
        value: "on",
        is_commented: true,
        type: "select",
        description: "Sets the transaction commit synchronization level.",
        options: ["off", "local", "remote_write", "remote_apply", "on"],
      },
      {
        name: "wal_sync_method",
        value: "fsync",
        is_commented: true,
        type: "select",
        description: "Method used to force WAL updates to disk.",
        options: ["open_datasync", "fdatasync", "fsync", "fsync_writethrough", "open_sync"],
      },
      {
        name: "full_page_writes",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Writes full disk pages to WAL during partial page updates.",
        options: ["on", "off"],
      },
      {
        name: "wal_log_hints",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Writes full pages to WAL during non-critical updates.",
        options: ["on", "off"],
      },
      {
        name: "wal_compression",
        value: "off",
        is_commented: true,
        type: "select",
        description: "Enables compression of full-page writes.",
        options: ["off", "pglz", "lz4", "zstd", "on"],
      },
      {
        name: "wal_init_zero",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Zero-fills new WAL files.",
        options: ["on", "off"],
      },
      {
        name: "wal_recycle",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Recycles WAL files instead of creating new ones.",
        options: ["on", "off"],
      },
      {
        name: "wal_buffers",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Memory used for WAL buffers.",
      },
      {
        name: "wal_writer_delay",
        value: "200ms",
        is_commented: true,
        type: "text",
        description: "Time between WAL writer rounds.",
      },
      {
        name: "wal_writer_flush_after",
        value: "1MB",
        is_commented: true,
        type: "text",
        description: "Amount of WAL written before triggering a flush.",
      },
      {
        name: "wal_skip_threshold",
        value: "2MB",
        is_commented: true,
        type: "text",
        description: "Threshold for skipping WAL flushes.",
      },
      {
        name: "commit_delay",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Microseconds to delay transaction commit.",
      },
      {
        name: "commit_siblings",
        value: "5",
        is_commented: true,
        type: "number",
        description: "Minimum concurrent open transactions before commit_delay is applied.",
      },
      {
        name: "checkpoint_timeout",
        value: "5min",
        is_commented: true,
        type: "text",
        description: "Maximum time between automatic WAL checkpoints.",
      },
      {
        name: "checkpoint_completion_target",
        value: "0.9",
        is_commented: true,
        type: "number",
        description: "Target duration for completing a checkpoint.",
      },
      {
        name: "checkpoint_flush_after",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Pages to write before flushing via checkpointer.",
      },
      {
        name: "checkpoint_warning",
        value: "30s",
        is_commented: true,
        type: "text",
        description: "Enables warnings if checkpoints are too frequent.",
      },
      {
        name: "max_wal_size",
        value: "1GB",
        is_commented: false,
        type: "text",
        description: "Maximum size the WAL is allowed to grow.",
      },
      {
        name: "min_wal_size",
        value: "80MB",
        is_commented: false,
        type: "text",
        description: "Minimum size to retain for recycling WAL files.",
      },
      {
        name: "recovery_prefetch",
        value: "try",
        is_commented: true,
        type: "select",
        description: "Prefetch pages referenced in the WAL.",
        options: ["on", "off", "try"],
      },
      {
        name: "wal_decode_buffer_size",
        value: "512kB",
        is_commented: true,
        type: "text",
        description: "Lookahead window used for WAL prefetching.",
      },
      {
        name: "archive_mode",
        value: "off",
        is_commented: true,
        type: "select",
        description: "Enables WAL archiving.",
        options: ["off", "on", "always"],
      },
      {
        name: "archive_library",
        value: "",
        is_commented: true,
        type: "text",
        description: "Library used to archive a WAL file.",
      },
      {
        name: "archive_command",
        value: "",
        is_commented: true,
        type: "text",
        description: "Command used to archive a WAL file.",
      },
      {
        name: "archive_timeout",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Forces a WAL file switch after this many seconds.",
      },
      {
        name: "restore_command",
        value: "",
        is_commented: true,
        type: "text",
        description: "Command to restore an archived WAL file.",
      },
      {
        name: "archive_cleanup_command",
        value: "",
        is_commented: true,
        type: "text",
        description: "Command to execute at every restartpoint during recovery.",
      },
      {
        name: "recovery_end_command",
        value: "",
        is_commented: true,
        type: "text",
        description: "Command to execute at completion of recovery.",
      },
      {
        name: "recovery_target",
        value: "",
        is_commented: true,
        type: "text",
        description: "Ends recovery as soon as a consistent state is reached.",
      },
      {
        name: "recovery_target_name",
        value: "",
        is_commented: true,
        type: "text",
        description: "Named restore point to which recovery proceeds.",
      },
      {
        name: "recovery_target_time",
        value: "",
        is_commented: true,
        type: "text",
        description: "Timestamp up to which recovery proceeds.",
      },
      {
        name: "recovery_target_xid",
        value: "",
        is_commented: true,
        type: "number",
        description: "Transaction ID up to which recovery proceeds.",
      },
      {
        name: "recovery_target_lsn",
        value: "",
        is_commented: true,
        type: "text",
        description: "WAL LSN up to which recovery proceeds.",
      },
      {
        name: "recovery_target_inclusive",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Specifies whether to stop just after or before the target.",
        options: ["on", "off"],
      },
      {
        name: "recovery_target_timeline",
        value: "latest",
        is_commented: true,
        type: "select",
        description: "Timeline ID to which recovery will proceed.",
        options: ["current", "latest"],
      },
      {
        name: "recovery_target_action",
        value: "pause",
        is_commented: true,
        type: "select",
        description: "Action to take when recovery target is reached.",
        options: ["pause", "promote", "shutdown"],
      },
      {
        name: "summarize_wal",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Runs WAL summarizer process.",
        options: ["on", "off"],
      },
      {
        name: "wal_summary_keep_time",
        value: "10d",
        is_commented: true,
        type: "text",
        description: "Time to keep old WAL summary files.",
      },
    ],
  },
  {
    title: "REPLICATION",
    fields: [
      {
        name: "max_wal_senders",
        value: "10",
        is_commented: true,
        type: "number",
        description: "Maximum number of walsender processes.",
      },
      {
        name: "max_replication_slots",
        value: "10",
        is_commented: true,
        type: "number",
        description: "Maximum number of replication slots.",
      },
      {
        name: "wal_keep_size",
        value: "0",
        is_commented: true,
        type: "text",
        description: "WAL size kept for standby servers.",
      },
      {
        name: "max_slot_wal_keep_size",
        value: "-1",
        is_commented: true,
        type: "text",
        description: "Maximum WAL size kept by replication slots.",
      },
      {
        name: "idle_replication_slot_timeout",
        value: "0",
        is_commented: true,
        type: "text",
        description: "Timeout for dropping inactive replication slots.",
      },
      {
        name: "wal_sender_timeout",
        value: "60s",
        is_commented: true,
        type: "text",
        description: "Timeout for replication connections.",
      },
      {
        name: "track_commit_timestamp",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Collects timestamps of transaction commits.",
        options: ["on", "off"],
      },
      {
        name: "synchronous_standby_names",
        value: "",
        is_commented: true,
        type: "text",
        description: "Specifies standby servers that provide synchronous replication.",
      },
      {
        name: "synchronized_standby_slots",
        value: "",
        is_commented: true,
        type: "text",
        description: "Streaming replication standby server slot names.",
      },
      {
        name: "primary_conninfo",
        value: "",
        is_commented: true,
        type: "text",
        description: "Connection string used by the standby server to connect to the primary.",
      },
      {
        name: "primary_slot_name",
        value: "",
        is_commented: true,
        type: "text",
        description: "Name of the replication slot on the primary server.",
      },
      {
        name: "hot_standby",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Allows queries during recovery on a standby server.",
        options: ["on", "off"],
      },
      {
        name: "max_standby_archive_delay",
        value: "30s",
        is_commented: true,
        type: "text",
        description: "Max delay before canceling queries when reading WAL from archive.",
      },
      {
        name: "max_standby_streaming_delay",
        value: "30s",
        is_commented: true,
        type: "text",
        description: "Max delay before canceling queries when reading streaming WAL.",
      },
      {
        name: "wal_receiver_create_temp_slot",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Creates temp slot if primary_slot_name is not set.",
        options: ["on", "off"],
      },
      {
        name: "wal_receiver_status_interval",
        value: "10s",
        is_commented: true,
        type: "text",
        description: "Interval for sending replies from standby to primary.",
      },
      {
        name: "hot_standby_feedback",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Sends info from standby to prevent query conflicts.",
        options: ["on", "off"],
      },
      {
        name: "wal_receiver_timeout",
        value: "60s",
        is_commented: true,
        type: "text",
        description: "Time the receiver waits for communication from primary.",
      },
      {
        name: "wal_retrieve_retry_interval",
        value: "5s",
        is_commented: true,
        type: "text",
        description: "Time to wait before retrying WAL retrieval.",
      },
      {
        name: "recovery_min_apply_delay",
        value: "0",
        is_commented: true,
        type: "text",
        description: "Minimum delay for applying changes during recovery.",
      },
      {
        name: "sync_replication_slots",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Enables slot synchronization from primary to physical standby.",
        options: ["on", "off"],
      },
      {
        name: "max_active_replication_origins",
        value: "10",
        is_commented: true,
        type: "number",
        description: "Maximum number of active replication origins.",
      },
      {
        name: "max_logical_replication_workers",
        value: "4",
        is_commented: true,
        type: "number",
        description: "Maximum number of logical replication workers.",
      },
      {
        name: "max_sync_workers_per_subscription",
        value: "2",
        is_commented: true,
        type: "number",
        description: "Maximum synchronization workers per subscription.",
      },
      {
        name: "max_parallel_apply_workers_per_subscription",
        value: "2",
        is_commented: true,
        type: "number",
        description: "Maximum parallel apply workers per subscription.",
      },
    ],
  },
  {
    title: "QUERY TUNING",
    fields: [
      {
        name: "enable_async_append",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of async append plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_bitmapscan",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of bitmap-scan plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_gathermerge",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of gather merge plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_hashagg",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of hashed aggregation plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_hashjoin",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of hash join plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_incremental_sort",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of incremental sort.",
        options: ["on", "off"],
      },
      {
        name: "enable_indexscan",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of index-scan plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_indexonlyscan",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of index-only-scan plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_material",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of materialization.",
        options: ["on", "off"],
      },
      {
        name: "enable_memoize",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of memoize nodes.",
        options: ["on", "off"],
      },
      {
        name: "enable_mergejoin",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of merge join plan types.",
        options: ["on", "off"],
      },
      {
        name: "enable_nestloop",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of nested-loop join plans.",
        options: ["on", "off"],
      },
      {
        name: "enable_parallel_append",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of parallel append.",
        options: ["on", "off"],
      },
      {
        name: "enable_parallel_hash",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of parallel hash joins.",
        options: ["on", "off"],
      },
      {
        name: "enable_partition_pruning",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables partition pruning during query planning.",
        options: ["on", "off"],
      },
      {
        name: "enable_partitionwise_join",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Enables partitionwise join.",
        options: ["on", "off"],
      },
      {
        name: "enable_partitionwise_aggregate",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Enables partitionwise aggregation.",
        options: ["on", "off"],
      },
      {
        name: "enable_presorted_aggregate",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables presorted aggregation.",
        options: ["on", "off"],
      },
      {
        name: "enable_seqscan",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of sequential scan plans.",
        options: ["on", "off"],
      },
      {
        name: "enable_sort",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of explicit sort steps.",
        options: ["on", "off"],
      },
      {
        name: "enable_tidscan",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables or disables planner's use of TID scan plans.",
        options: ["on", "off"],
      },
      {
        name: "enable_group_by_reordering",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables reordering of GROUP BY elements.",
        options: ["on", "off"],
      },
      {
        name: "enable_distinct_reordering",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables reordering of DISTINCT elements.",
        options: ["on", "off"],
      },
      {
        name: "enable_self_join_elimination",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables elimination of unnecessary self-joins.",
        options: ["on", "off"],
      },
      {
        name: "seq_page_cost",
        value: "1.0",
        is_commented: true,
        type: "number",
        description: "Estimated cost of a disk page fetch sequentially.",
      },
      {
        name: "random_page_cost",
        value: "4.0",
        is_commented: true,
        type: "number",
        description: "Estimated cost of a non-sequentially-fetched disk page.",
      },
      {
        name: "cpu_tuple_cost",
        value: "0.01",
        is_commented: true,
        type: "number",
        description: "Estimated cost of processing each tuple (row) during a query.",
      },
      {
        name: "cpu_index_tuple_cost",
        value: "0.005",
        is_commented: true,
        type: "number",
        description: "Estimated cost of processing each index entry during an index scan.",
      },
      {
        name: "cpu_operator_cost",
        value: "0.0025",
        is_commented: true,
        type: "number",
        description: "Estimated cost of processing each operator or function executed during a query.",
      },
      {
        name: "parallel_setup_cost",
        value: "1000.0",
        is_commented: true,
        type: "number",
        description: "Estimated cost of launching parallel worker processes.",
      },
      {
        name: "parallel_tuple_cost",
        value: "0.1",
        is_commented: true,
        type: "number",
        description: "Estimated cost of passing a tuple from a parallel worker to the leader.",
      },
      {
        name: "min_parallel_table_scan_size",
        value: "8MB",
        is_commented: true,
        type: "text",
        description: "Minimum amount of table data to consider for a parallel scan.",
      },
      {
        name: "min_parallel_index_scan_size",
        value: "512kB",
        is_commented: true,
        type: "text",
        description: "Minimum amount of index data to consider for a parallel scan.",
      },
      {
        name: "effective_cache_size",
        value: "4GB",
        is_commented: true,
        type: "text",
        description: "Planner's assumption about the effective size of the disk cache.",
      },
      {
        name: "jit_above_cost",
        value: "100000",
        is_commented: true,
        type: "number",
        description: "Cost threshold for performing JIT compilation.",
      },
      {
        name: "jit_inline_above_cost",
        value: "500000",
        is_commented: true,
        type: "number",
        description: "Cost threshold for JIT inlining of small functions.",
      },
      {
        name: "jit_optimize_above_cost",
        value: "500000",
        is_commented: true,
        type: "number",
        description: "Cost threshold for using expensive JIT optimizations.",
      },
      {
        name: "geqo",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables genetic query optimization.",
        options: ["on", "off"],
      },
      {
        name: "geqo_threshold",
        value: "12",
        is_commented: true,
        type: "number",
        description: "Number of FROM items to trigger genetic query optimization.",
      },
      {
        name: "geqo_effort",
        value: "5",
        is_commented: true,
        type: "number",
        description: "GEQO effort parameter (range 1-10).",
      },
      {
        name: "geqo_pool_size",
        value: "0",
        is_commented: true,
        type: "number",
        description: "GEQO pool size.",
      },
      {
        name: "geqo_generations",
        value: "0",
        is_commented: true,
        type: "number",
        description: "GEQO number of generations.",
      },
      {
        name: "geqo_selection_bias",
        value: "2.0",
        is_commented: true,
        type: "number",
        description: "GEQO selection bias (range 1.5-2.0).",
      },
      {
        name: "geqo_seed",
        value: "0.0",
        is_commented: true,
        type: "number",
        description: "GEQO random seed.",
      },
      {
        name: "default_statistics_target",
        value: "100",
        is_commented: true,
        type: "number",
        description: "Default statistics target for table columns.",
      },
      {
        name: "constraint_exclusion",
        value: "partition",
        is_commented: true,
        type: "select",
        description: "Use constraint exclusion for query optimization.",
        options: ["on", "off", "partition"],
      },
      {
        name: "cursor_tuple_fraction",
        value: "0.1",
        is_commented: true,
        type: "number",
        description: "Planner's estimate of the fraction of a cursor's rows that will be retrieved.",
      },
      {
        name: "from_collapse_limit",
        value: "8",
        is_commented: true,
        type: "number",
        description: "Maximum number of FROM items to collapse into the main join tree.",
      },
      {
        name: "jit",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Allow JIT compilation.",
        options: ["on", "off"],
      },
      {
        name: "join_collapse_limit",
        value: "8",
        is_commented: true,
        type: "number",
        description: "Maximum number of JOIN items to collapse into the main join tree.",
      },
      {
        name: "plan_cache_mode",
        value: "auto",
        is_commented: true,
        type: "select",
        description: "Controls the planner's choice between custom and generic plans.",
        options: ["auto", "force_generic_plan", "force_custom_plan"],
      },
      {
        name: "recursive_worktable_factor",
        value: "10.0",
        is_commented: true,
        type: "number",
        description: "Estimated size factor for recursive CTEs.",
      },
    ],
  },
  {
    title: "REPORTING AND LOGGING",
    fields: [
      {
        name: "log_destination",
        value: "stderr",
        is_commented: true,
        type: "text",
        description: "Valid values are combinations of stderr, csvlog, jsonlog, syslog, and eventlog.",
        options: ["stderr", "csvlog", "jsonlog", "syslog", "eventlog"],
      },
      {
        name: "logging_collector",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Enable capturing of stderr, jsonlog, and csvlog into log files.",
        options: ["on", "off"],
      },
      {
        name: "log_directory",
        value: "log",
        is_commented: true,
        type: "path",
        description: "Directory where log files are written.",
      },
      {
        name: "log_filename",
        value: "postgresql-%Y-%m-%d_%H%M%S.log",
        is_commented: true,
        type: "text",
        description: "Log file name pattern.",
      },
      {
        name: "log_file_mode",
        value: "0640",
        is_commented: false,
        type: "text",
        description: "Creation mode for log files.",
      },
      {
        name: "log_rotation_age",
        value: "1d",
        is_commented: true,
        type: "text",
        description: "Automatic rotation of logfiles will happen after that time.",
      },
      {
        name: "log_rotation_size",
        value: "10MB",
        is_commented: true,
        type: "text",
        description: "Automatic rotation of logfiles will happen after that much log output.",
      },
      {
        name: "log_truncate_on_rotation",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Truncate existing log files on time-driven rotation.",
        options: ["on", "off"],
      },
      {
        name: "syslog_facility",
        value: "LOCAL0",
        is_commented: true,
        type: "text",
        description: "Syslog facility to be used.",
      },
      {
        name: "syslog_ident",
        value: "postgres",
        is_commented: true,
        type: "text",
        description: "Syslog identity program name.",
      },
      {
        name: "syslog_sequence_numbers",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Adds a sequence number to syslog messages.",
        options: ["on", "off"],
      },
      {
        name: "syslog_split_messages",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Splits long syslog messages.",
        options: ["on", "off"],
      },
      {
        name: "event_source",
        value: "PostgreSQL",
        is_commented: true,
        type: "text",
        description: "Event source name for Windows Event Log.",
      },
      {
        name: "log_min_messages",
        value: "warning",
        is_commented: true,
        type: "select",
        description: "Minimum severity level of messages to be logged.",
        options: [
          "debug5",
          "debug4",
          "debug3",
          "debug2",
          "debug1",
          "info",
          "notice",
          "warning",
          "error",
          "log",
          "fatal",
          "panic",
        ],
      },
      {
        name: "log_min_error_statement",
        value: "error",
        is_commented: true,
        type: "select",
        description: "Minimum severity level of messages that trigger logging of the SQL statement causing the error.",
        options: [
          "debug5",
          "debug4",
          "debug3",
          "debug2",
          "debug1",
          "info",
          "notice",
          "warning",
          "error",
          "log",
          "fatal",
          "panic",
        ],
      },
      {
        name: "log_min_duration_statement",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Logs statements running at least this number of milliseconds.",
      },
      {
        name: "log_min_duration_sample",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Logs a sample of statements running at least this number of milliseconds.",
      },
      {
        name: "log_statement_sample_rate",
        value: "1.0",
        is_commented: true,
        type: "number",
        description: "Fraction of logged statements exceeding log_min_duration_sample to be logged.",
      },
      {
        name: "log_transaction_sample_rate",
        value: "0.0",
        is_commented: true,
        type: "number",
        description: "Fraction of transactions whose statements are logged regardless of duration.",
      },
      {
        name: "log_startup_progress_interval",
        value: "10s",
        is_commented: true,
        type: "text",
        description: "Time between progress updates for long-running startup operations.",
      },
      {
        name: "debug_print_parse",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Prints parse trees.",
        options: ["on", "off"],
      },
      {
        name: "debug_print_rewritten",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Prints query rewrite output.",
        options: ["on", "off"],
      },
      {
        name: "debug_print_plan",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Prints execution plans.",
        options: ["on", "off"],
      },
      {
        name: "debug_pretty_print",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Indents debug output.",
        options: ["on", "off"],
      },
      {
        name: "log_autovacuum_min_duration",
        value: "10min",
        is_commented: true,
        type: "text",
        description: "Logs autovacuum activity exceeding this duration.",
      },
      {
        name: "log_checkpoints",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Logs checkpoints and restartpoints.",
        options: ["on", "off"],
      },
      {
        name: "log_connections",
        value: "",
        is_commented: true,
        type: "toggle",
        description: "Logs aspects of connection setup.",
        options: ["on", "off"],
      },
      {
        name: "log_disconnections",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs disconnections.",
        options: ["on", "off"],
      },
      {
        name: "log_duration",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs duration of every completed SQL statement.",
        options: ["on", "off"],
      },
      {
        name: "log_error_verbosity",
        value: "default",
        is_commented: true,
        type: "select",
        description: "Amount of detail logged for errors.",
        options: ["terse", "default", "verbose"],
      },
      {
        name: "log_hostname",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs client hostnames.",
        options: ["on", "off"],
      },
      {
        name: "log_line_prefix",
        value: "%m [%p] ",
        is_commented: true,
        type: "text",
        description: "Prefix applied to each log line.",
      },
      {
        name: "log_lock_waits",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs lock waits exceeding deadlock_timeout.",
        options: ["on", "off"],
      },
      {
        name: "log_lock_failures",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs lock failures.",
        options: ["on", "off"],
      },
      {
        name: "log_recovery_conflict_waits",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs standby recovery conflict waits.",
        options: ["on", "off"],
      },
      {
        name: "log_parameter_max_length",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Limits logged bind-parameter values to N bytes.",
      },
      {
        name: "log_parameter_max_length_on_error",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Limits logged bind-parameter values on error.",
      },
      {
        name: "log_statement",
        value: "none",
        is_commented: true,
        type: "select",
        description: "Controls which SQL statements are logged.",
        options: ["none", "ddl", "mod", "all"],
      },
      {
        name: "log_replication_commands",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs replication commands.",
        options: ["on", "off"],
      },
      {
        name: "log_temp_files",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Logs the creation of temporary files larger than specified size.",
      },
      {
        name: "log_timezone",
        value: "Europe/Istanbul",
        is_commented: false,
        type: "text",
        description: "Sets the time zone used for log timestamps.",
      },
      {
        name: "cluster_name",
        value: "",
        is_commented: true,
        type: "text",
        description: "Name added to process titles if nonempty.",
      },
      {
        name: "update_process_title",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Updates the process title on operating systems that support it.",
        options: ["on", "off"],
      },
    ],
  },
  {
    title: "STATISTICS",
    fields: [
      {
        name: "track_activities",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables tracking of currently executing commands.",
        options: ["on", "off"],
      },
      {
        name: "track_activity_query_size",
        value: "1024",
        is_commented: true,
        type: "number",
        description: "Maximum size of string recorded for track_activities.",
      },
      {
        name: "track_counts",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables tracking of database activity statistics.",
        options: ["on", "off"],
      },
      {
        name: "track_cost_delay_timing",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Tracks cost delay timing.",
        options: ["on", "off"],
      },
      {
        name: "track_io_timing",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Tracks I/O read and write times.",
        options: ["on", "off"],
      },
      {
        name: "track_wal_io_timing",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Tracks WAL I/O times.",
        options: ["on", "off"],
      },
      {
        name: "track_functions",
        value: "none",
        is_commented: true,
        type: "select",
        description: "Tracks function call counts and time used.",
        options: ["none", "pl", "all"],
      },
      {
        name: "stats_fetch_consistency",
        value: "cache",
        is_commented: true,
        type: "select",
        description: "Statistics fetch consistency method.",
        options: ["cache", "none", "snapshot"],
      },
      {
        name: "compute_query_id",
        value: "auto",
        is_commented: true,
        type: "select",
        description: "Computes a query identifier to associate metrics to queries.",
        options: ["on", "off", "auto"],
      },
      {
        name: "log_statement_stats",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs cumulative performance statistics for each statement.",
        options: ["on", "off"],
      },
      {
        name: "log_parser_stats",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs parser performance statistics.",
        options: ["on", "off"],
      },
      {
        name: "log_planner_stats",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs planner performance statistics.",
        options: ["on", "off"],
      },
      {
        name: "log_executor_stats",
        value: "off",
        is_commented: true,
        type: "toggle",
        description: "Logs executor performance statistics.",
        options: ["on", "off"],
      },
    ],
  },
  {
    title: "VACUUMING",
    fields: [
      {
        name: "autovacuum",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables autovacuum subprocess.",
        options: ["on", "off"],
      },
      {
        name: "autovacuum_worker_slots",
        value: "16",
        is_commented: false,
        type: "number",
        description: "Number of autovacuum worker slots to allocate.",
      },
      {
        name: "autovacuum_max_workers",
        value: "3",
        is_commented: true,
        type: "number",
        description: "Maximum number of autovacuum subprocesses.",
      },
      {
        name: "autovacuum_naptime",
        value: "1min",
        is_commented: true,
        type: "text",
        description: "Minimum delay between autovacuum runs on any given database.",
      },
      {
        name: "autovacuum_vacuum_threshold",
        value: "50",
        is_commented: true,
        type: "number",
        description: "Minimum number of row updates before triggering vacuum.",
      },
      {
        name: "autovacuum_vacuum_insert_threshold",
        value: "1000",
        is_commented: true,
        type: "number",
        description: "Minimum number of row inserts before triggering vacuum.",
      },
      {
        name: "autovacuum_analyze_threshold",
        value: "50",
        is_commented: true,
        type: "number",
        description: "Minimum number of row updates before triggering analyze.",
      },
      {
        name: "autovacuum_vacuum_scale_factor",
        value: "0.2",
        is_commented: true,
        type: "number",
        description: "Fraction of table size before triggering vacuum.",
      },
      {
        name: "autovacuum_vacuum_insert_scale_factor",
        value: "0.2",
        is_commented: true,
        type: "number",
        description: "Fraction of unfrozen pages before insert vacuum.",
      },
      {
        name: "autovacuum_analyze_scale_factor",
        value: "0.1",
        is_commented: true,
        type: "number",
        description: "Fraction of table size before triggering analyze.",
      },
      {
        name: "autovacuum_vacuum_max_threshold",
        value: "100000000",
        is_commented: true,
        type: "number",
        description: "Max number of row updates before vacuum.",
      },
      {
        name: "autovacuum_freeze_max_age",
        value: "200000000",
        is_commented: true,
        type: "number",
        description: "Maximum XID age before forced vacuum.",
      },
      {
        name: "autovacuum_multixact_freeze_max_age",
        value: "400000000",
        is_commented: true,
        type: "number",
        description: "Maximum multixact age before forced vacuum.",
      },
      {
        name: "autovacuum_vacuum_cost_delay",
        value: "2ms",
        is_commented: true,
        type: "text",
        description: "Default vacuum cost delay for autovacuum.",
      },
      {
        name: "autovacuum_vacuum_cost_limit",
        value: "-1",
        is_commented: true,
        type: "number",
        description: "Default vacuum cost limit for autovacuum.",
      },
      {
        name: "vacuum_cost_delay",
        value: "0",
        is_commented: true,
        type: "number",
        description: "Time to sleep when the cost limit is exceeded during vacuum.",
      },
      {
        name: "vacuum_cost_page_hit",
        value: "1",
        is_commented: true,
        type: "number",
        description: "Estimated cost for vacuuming a buffer found in shared cache.",
      },
      {
        name: "vacuum_cost_page_miss",
        value: "2",
        is_commented: true,
        type: "number",
        description: "Estimated cost for vacuuming a buffer that has to be read from disk.",
      },
      {
        name: "vacuum_cost_page_dirty",
        value: "20",
        is_commented: true,
        type: "number",
        description: "Estimated cost for modifying a block previously clean.",
      },
      {
        name: "vacuum_cost_limit",
        value: "200",
        is_commented: true,
        type: "number",
        description: "Accumulated cost that will cause the vacuuming process to sleep.",
      },
      {
        name: "vacuum_truncate",
        value: "on",
        is_commented: true,
        type: "toggle",
        description: "Enables truncation of empty pages at the end of a table after vacuum.",
        options: ["on", "off"],
      },
      {
        name: "vacuum_freeze_table_age",
        value: "150000000",
        is_commented: true,
        type: "number",
        description: "Age at which VACUUM should scan the whole table to freeze tuples.",
      },
      {
        name: "vacuum_freeze_min_age",
        value: "50000",
        is_commented: true,
        type: "number",
        description: "Minimum cutoff age for freezing tuples.",
      },
    ],
  },
];
